#!/bin/sh -e

WHEELS_DIR=$1

# Headers
echo "<!DOCTYPE html>" > ${WHEELS_DIR}/index.html
echo "<html>" >> ${WHEELS_DIR}/index.html
echo "  <body>" >> ${WHEELS_DIR}/index.html

# Loop over all the packages
for d in $(find ${WHEELS_DIR} -type d -mindepth 1 -maxdepth 1); do
  # Generate index for the package
  echo "<!DOCTYPE html>" > ${d}/index.html
  echo "<html>" >> ${d}/index.html
  echo "  <body>" >> ${d}/index.html

  # Loop over all the wheels
  for w in $(find ${d} -type f -name "*.whl"); do
    echo "    <a href=\"./$(basename ${w})\">$(basename ${w})</a>" >> ${d}/index.html
  done

  # End the page
  echo "  </body>" >> ${d}/index.html
  echo "</html>" >> ${d}/index.html

  echo "    <a href=\"./$(basename ${d})/\">$(basename ${d})</a>" >> ${WHEELS_DIR}/index.html
done

# End the page
echo "  </body>" >> ${WHEELS_DIR}/index.html
echo "</html>" >> ${WHEELS_DIR}/index.html
