name: publish
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  pages:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - run: ./tools/wheel-index alpine-3.15
      - uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          folder: public
